name: Github Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Output job info
        run: |
          echo "This job was triggered by event ${{ github.event_name }}"
          echo "The name of your branch is ${{ github.ref }} in repository ${{ github.repository }}"

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List files in repository
        run: |
          echo "The repository contains the following:"
          tree
