name: CI Build for Docker Action
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Docker container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@rmcmanus'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
